# NLP Preprocessing
## Women's Clothing E-Commerce Reviews Sentiment Analysis

**Team Member:** Hadia Nasir

### Objectives
- Lowercase Conversion
- Regex Cleaning
- Remove Special Characters
- Tokenization
- Stop-word Removal
- Lemmatization

Dataset Source:
Cleaned_Reviews_File.csv

## Task 1 (Lowercase Conversion)

In [7]:
# Import required libraries
import pandas as pd
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [9]:
# Download required NLTK packages (Run only once)

In [45]:
# Download required NLTK packages (Run only once)

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\GIFT\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\GIFT\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\GIFT\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\GIFT\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\GIFT\AppData\Roaming\nltk_data...

True

In [13]:
# Load the cleaned dataset

df = pd.read_csv("Cleaned_Reviews_File.csv")

In [15]:
# Display the first five records

df.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Sentiment,Age_Group
0,767,0.185185,No Title,Absolutely wonderful - silky and sexy and comf...,4,1,-0.444977,2,2,5,Positive,Young
1,1080,0.197531,No Title,Love this dress! it's sooo pretty. i happene...,5,1,0.256270,0,1,3,Positive,Young
2,1077,0.518519,Some major design flaws,I had such high hopes for this dress and reall...,3,0,-0.444977,0,1,3,Neutral,Middle
3,1049,0.395062,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,-0.444977,1,0,13,Positive,Middle
4,847,0.358025,Flattering shirt,This shirt is very flattering to all due to th...,5,1,0.606893,0,4,0,Positive,Middle

In [17]:
# Display sample reviews before preprocessing

df["Review Text"].head()

0    Absolutely wonderful - silky and sexy and comf...
1    Love this dress!  it's sooo pretty.  i happene...
2    I had such high hopes for this dress and reall...
3    I love, love, love this jumpsuit. it's fun, fl...
4    This shirt is very flattering to all due to th...
Name: Review Text, dtype: object

In [19]:
# Convert all review text to lowercase

df["Review Text"] = df["Review Text"].str.lower()

In [21]:
# Display reviews after lowercase conversion

df["Review Text"].head(10)

0    absolutely wonderful - silky and sexy and comf...
1    love this dress!  it's sooo pretty.  i happene...
2    i had such high hopes for this dress and reall...
3    i love, love, love this jumpsuit. it's fun, fl...
4    this shirt is very flattering to all due to th...
5    i love tracy reese dresses, but this one is no...
6    i aded this in my basket at hte last mintue to...
7    i ordered this in carbon for store pick up, an...
8    i love this dress. i usually get an xs but it ...
9    i'm 5"5' and 125 lbs. i ordered the s petite t...
Name: Review Text, dtype: object

In [23]:
# Display the first five records

df.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Sentiment,Age_Group
0,767,0.185185,No Title,absolutely wonderful - silky and sexy and comf...,4,1,-0.444977,2,2,5,Positive,Young
1,1080,0.197531,No Title,love this dress! it's sooo pretty. i happene...,5,1,0.256270,0,1,3,Positive,Young
2,1077,0.518519,Some major design flaws,i had such high hopes for this dress and reall...,3,0,-0.444977,0,1,3,Neutral,Middle
3,1049,0.395062,My favorite buy!,"i love, love, love this jumpsuit. it's fun, fl...",5,1,-0.444977,1,0,13,Positive,Middle
4,847,0.358025,Flattering shirt,this shirt is very flattering to all due to th...,5,1,0.606893,0,4,0,Positive,Middle

## Task 2 (Regex Cleaning)

In [31]:
# Remove URLs and extra white spaces using regex

df["Review Text"] = (
    df["Review Text"]
    .str.replace(r"http\S+|www\S+", "", regex=True)   # Remove URLs
    .str.replace(r"\s+", " ", regex=True)             # Replace multiple spaces with a single space
    .str.strip()                                      # Remove leading/trailing spaces
)

In [33]:
# Display sample reviews after regex cleaning

df["Review Text"].head(10)

0    absolutely wonderful - silky and sexy and comf...
1    love this dress! it's sooo pretty. i happened ...
2    i had such high hopes for this dress and reall...
3    i love, love, love this jumpsuit. it's fun, fl...
4    this shirt is very flattering to all due to th...
5    i love tracy reese dresses, but this one is no...
6    i aded this in my basket at hte last mintue to...
7    i ordered this in carbon for store pick up, an...
8    i love this dress. i usually get an xs but it ...
9    i'm 5"5' and 125 lbs. i ordered the s petite t...
Name: Review Text, dtype: object

## Task 3 (Remove Special Characters)

In [38]:
# Remove special characters from review text

df["Review Text"] = df["Review Text"].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)

In [40]:
# Display sample reviews after removing special characters

df["Review Text"].head(10)

0    absolutely wonderful  silky and sexy and comfo...
1    love this dress its sooo pretty i happened to ...
2    i had such high hopes for this dress and reall...
3    i love love love this jumpsuit its fun flirty ...
4    this shirt is very flattering to all due to th...
5    i love tracy reese dresses but this one is not...
6    i aded this in my basket at hte last mintue to...
7    i ordered this in carbon for store pick up and...
8    i love this dress i usually get an xs but it r...
9    im 55 and 125 lbs i ordered the s petite to ma...
Name: Review Text, dtype: object

## Task4 (Tokenization)

In [47]:
# Tokenize review text into individual words

df["Review Tokens"] = df["Review Text"].apply(word_tokenize)

In [49]:
# Display tokenized reviews

df[["Review Text", "Review Tokens"]].head()

,Review Text,Review Tokens
0,absolutely wonderful silky and sexy and comfo...,"[absolutely, wonderful, silky, and, sexy, and,..."
1,love this dress its sooo pretty i happened to ...,"[love, this, dress, its, sooo, pretty, i, happ..."
2,i had such high hopes for this dress and reall...,"[i, had, such, high, hopes, for, this, dress, ..."
3,i love love love this jumpsuit its fun flirty ...,"[i, love, love, love, this, jumpsuit, its, fun..."
4,this shirt is very flattering to all due to th...,"[this, shirt, is, very, flattering, to, all, d..."

## Task 5 (Stop-word Removal)

In [52]:
# Initialize English stop words

stop_words = set(stopwords.words('english'))

In [54]:
# Remove stop words from tokenized reviews

df["Review Tokens"] = df["Review Tokens"].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [56]:
# Display reviews after stop-word removal

df[["Review Text", "Review Tokens"]].head()

,Review Text,Review Tokens
0,absolutely wonderful silky and sexy and comfo...,"[absolutely, wonderful, silky, sexy, comfortable]"
1,love this dress its sooo pretty i happened to ...,"[love, dress, sooo, pretty, happened, find, st..."
2,i had such high hopes for this dress and reall...,"[high, hopes, dress, really, wanted, work, ini..."
3,i love love love this jumpsuit its fun flirty ...,"[love, love, love, jumpsuit, fun, flirty, fabu..."
4,this shirt is very flattering to all due to th...,"[shirt, flattering, due, adjustable, front, ti..."

## Task 6 (Apply Lemmatization)

In [59]:
# Initialize the WordNet lemmatizer

lemmatizer = WordNetLemmatizer()

In [61]:
# Apply lemmatization to tokenized reviews

df["Review Tokens"] = df["Review Tokens"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [69]:
df[["Review Text", "Review Tokens"]].head(10)

,Review Text,Review Tokens
0,absolutely wonderful silky and sexy and comfo...,"[absolutely, wonderful, silky, sexy, comfortable]"
1,love this dress its sooo pretty i happened to ...,"[love, dress, sooo, pretty, happened, find, st..."
2,i had such high hopes for this dress and reall...,"[high, hope, dress, really, wanted, work, init..."
3,i love love love this jumpsuit its fun flirty ...,"[love, love, love, jumpsuit, fun, flirty, fabu..."
4,this shirt is very flattering to all due to th...,"[shirt, flattering, due, adjustable, front, ti..."
5,i love tracy reese dresses but this one is not...,"[love, tracy, reese, dress, one, petite, 5, fo..."
6,i aded this in my basket at hte last mintue to...,"[aded, basket, hte, last, mintue, see, would, ..."
7,i ordered this in carbon for store pick up and...,"[ordered, carbon, store, pick, ton, stuff, alw..."
8,i love this dress i usually get an xs but it r...,"[love, dress, usually, get, x, run, little, sn..."
9,im 55 and 125 lbs i ordered the s petite to ma...,"[im, 55, 125, lb, ordered, petite, make, sure,..."

In [73]:
# Convert token lists back into text for TF-IDF

df["Processed Text"] = df["Review Tokens"].apply(lambda tokens: " ".join(tokens))

In [77]:
# Display processed text

df[["Review Tokens", "Processed Text"]].head()

,Review Tokens,Processed Text
0,"[absolutely, wonderful, silky, sexy, comfortable]",absolutely wonderful silky sexy comfortable
1,"[love, dress, sooo, pretty, happened, find, st...",love dress sooo pretty happened find store im ...
2,"[high, hope, dress, really, wanted, work, init...",high hope dress really wanted work initially o...
3,"[love, love, love, jumpsuit, fun, flirty, fabu...",love love love jumpsuit fun flirty fabulous ev...
4,"[shirt, flattering, due, adjustable, front, ti...",shirt flattering due adjustable front tie perf...

In [79]:
# Save the preprocessed dataset

df.to_csv("Preprocessed_Reviews_File.csv", index=False)

print("Preprocessed dataset saved successfully.")

Preprocessed dataset saved successfully.

## Phase 4 Completed Successfully

The following NLP preprocessing tasks have been completed:

- Lowercase Conversion
- Regex Cleaning
- Special Character Removal
- Tokenization
- Stop-word Removal
- Lemmatization

### Output

The preprocessed dataset has been successfully generated and saved as:

**Preprocessed_Reviews_File.csv**

This dataset will be used in **Phase 5 (Feature Engineering)** to perform TF-IDF Vectorization, Unigram Generation, and Bigram Generation.